//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawPipe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrawPipe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;pipe&gt;
        ///  &lt;pipeType id=&quot;1&quot; name=&quot;одношовная&quot; &gt;
        ///    &lt;key name=&quot;одношовная&quot;&gt;986001&lt;/key&gt;
        ///  &lt;/pipeType&gt;
        ///  &lt;pipeType id=&quot;2&quot; name=&quot;двухшовная&quot; &gt;
        ///    &lt;key name=&quot;двухшовная&quot;&gt;986101&lt;/key&gt;
        ///  &lt;/pipeType&gt;
        ///  &lt;pipeType id=&quot;3&quot; name=&quot;безшовная&quot; &gt;
        ///    &lt;key name=&quot;безшовная&quot;&gt;985801&lt;/key&gt;
        ///  &lt;/pipeType&gt;
        ///  &lt;pipeType id=&quot;4&quot; name=&quot;С нераспознанным швом&quot; &gt;
        ///    &lt;key name=&quot;С нераспознанным швом&quot;&gt;986501&lt;/key&gt;
        ///  &lt;/pipeType&gt;
        ///  &lt;pipeType id=&quot;5&quot; name=&quot;Спиральношовная&quot; &gt;
        ///    &lt;key name= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TypePipe {
            get {
                return ResourceManager.GetString("TypePipe", resourceCulture);
            }
        }
    }
}
